# Generated by Django 5.2 on 2025-05-17 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('rides', 'Rides'), ('food', 'Food'), ('route', 'Route')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
